### ISSUE TITLE
Trying to compile and run this project and running into errors

### ISSUE THREAD

**Issue by cachemoney** [winkerVSbecks/storybook-blocks#1]
Hi Varun, I am attempting to follow your blog post and compile and start this project. I can't get past the initial steps of starting the project.  Tested this on 2 different MacBooks(Catlina and Big Sur) and running into the same identical issues.

1. a different version of babel-loader was detected higher up in the tree (see screenshot below)
        a)  Followed yarn's suggested solution was to add SKIP_PREFLIGHT_CHECK=true into a .env file.  This allowed me to go into the next step.
2.  Then after running `yarn start` the app won't load. I see these errors in the console. (both in the latest versions of Safari and Firefox) see screenshot below.

I am open to suggestions to help continue following the next steps of your blog post.

Thanks! 

<img width="928" alt="InitialCompile_Babel-loader-error" src="https://user-images.githubusercontent.com/477635/148002106-f6729481-c0af-4bac-ba7a-bfc0085755fb.png">
<img width="1266" alt="Noisematerial-Mesh-Error" src="https://user-images.githubusercontent.com/477635/148002110-e78cc9ba-c6ee-4e44-9262-726a3144bf86.png">
w

**Comment by winkerVSbecks** [comment]
`SKIP_PREFLIGHT_CHECK=true` is a known issue. Indeed you need to use that. Or you can update your scripts to something like this:

```
"start": "SKIP_PREFLIGHT_CHECK=true react-scripts start"
"build": "SKIP_PREFLIGHT_CHECK=true react-scripts build"
```

**Comment by winkerVSbecks** [comment]
@cachemoney so I just noticed a bug since I was primarily using storybook for the post. An import was missing. I just pushed a fix. Pull the latest and it should work.

**Comment by cachemoney** [comment]
thanks! the changes worked
